import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar3 from "../components/Navbar3";
import Footer from "../components/Footer";
import { AppProvider } from "../context/AppContext";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppProvider>

        <Navbar3/>
        {children}
         <Toaster position="top-right" />
        <Footer/>
        </AppProvider>
        </body>
    </html>
  );
}
